image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

deploy_nonprod:
  stage: build
  only:
    - developemt
  script:
    - ./scripts/deploy_nonprod.sh

deploy_prod:
  stage: build
  only:
    - production
  when: manual
  script:
    - ./scripts/deploy_prod.sh