image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

stages:
  - deploy_nonprod
  - deploy_prod

deploy_nonprod:
  stage: deploy_nonprod
  only:
    - development
  before_script:
    - apt-get install wget
    - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
    - sha256sum aws-sam-cli-linux-x86_64.zip
    - unzip -qq aws-sam-cli-linux-x86_64.zip -d sam-installation
    - ./sam-installation/install
    - sam --version
  script:
    - chmod +x scripts/deploy_nonprod.sh
    - ./scripts/deploy_nonprod.sh

deploy_prod:
  stage: deploy_prod
  only:
    - production
  when: manual
  script:
    - chmod +x scripts/deploy_prod.sh
    - ./scripts/deploy_prod.sh